- .github/workflows/antsibull-docs.yml
- .github/workflows/antsibull.yml
This should ensure that we don't accidentally break compatibility with older verisons of antsibull-docs that depend on antsibull-core 1.x.y. Obviously this isn't 100% covering everything, but it's a lot better than nothing :)
> CI: run some basic tests against antsibull-docs 1.0.0 and antsibull 0.44.0

- changelogs/fragments/1.2.0.yml
- changelogs/fragments/7-config.yml
- pyproject.toml
- src/antsibull_core/app_context.py
- src/antsibull_core/config.py
- src/antsibull_core/schemas/config.py
- src/antsibull_core/schemas/context.py
So that dependent projects can have their own config without it having to be defined globally for all projects using antsibull-core.
> Improve config file mechanism

- changelogs/fragments/10-python_requires.yml
- src/antsibull_core/dependency_files.py
This is needed so that the build info can extract that info from ansible-core instead of having to guess it (which needs to be coordinated with ansible-core).
> Allow to write python_requires into deps and build files

- changelogs/fragments/11-copy-fix.yml
- mypy.ini
- pyproject.toml
- src/antsibull_core/utils/io.py
See https://github.com/ansible-community/antsibull/pull/450
> Fix async file copying helper; use aiofiles typeshed definitions instead of ignoring the package

- changelogs/fragments/14-StrOrBytesPath.yaml
- src/antsibull_core/utils/io.py
- src/antsibull_core/yaml.py
StrOrBytesPath encompasses str, bytes, and PathLike file names, which are valid inputs to open(). There's likely more of these that should be fixed, but this is some of them. I'd like to use pathlib in my source distribution code so that's my motivation here :).
> Fix overly restrictive file name types

- src/antsibull_core/ansible_core.py
- src/antsibull_core/app_context.py
- src/antsibull_core/args.py
- src/antsibull_core/collections.py
- src/antsibull_core/config.py
- src/antsibull_core/dependency_files.py
- src/antsibull_core/filesystem.py
- src/antsibull_core/galaxy.py
- src/antsibull_core/logging.py
- src/antsibull_core/schemas/config.py
- src/antsibull_core/schemas/validators.py
- src/antsibull_core/tarball.py
- src/antsibull_core/utils/collections.py
- src/antsibull_core/utils/hashing.py
- src/antsibull_core/utils/http.py
- src/antsibull_core/venv.py
See https://github.com/ansible-community/antsibull-core/pull/18#issuecomment-1340037669
I didn't change the files in antsibull_core.schemas since Pydantic needs runtime access to the type definitions.
I also didn't change `typing.Mapping` and friends to `collections.abc.Mapping` since it's more to type :)
> typing: use simpler syntax where possible

- changelogs/fragments/40-subprocess.yaml
- src/antsibull_core/subprocess_util.py
- tests/units/test_subprocess_util.py
This adds code to run subprocesses asynchronously and integrates with the logger. stdout and stderr are logged in real time and always captured. We return a CompletedProcess object like regular subprocess does.
Relates: https://github.com/ansible-community/antsibull-core/issues/34
> add subprocess_util module to replace sh

- pyproject.toml
Things like `if TYPE_CHECKING` which we use various places in the
project artificially lower the coverage percentage.
> CI: exclude never executed code from coverage

- changelogs/fragments/50-new-venv.yaml
- src/antsibull_core/venv.py
- tests/functional/test_venv.py
- Deprecate the `get_command` methods on VenvRunner and FakeVenvRunner
- Add new `async_log_run` and `log_run` methods to replace the former.
These work the same as their counterparts in
`antsibull_core.subprocess_util`, but the VenvRunner version enforces
a clean environment and requires paths to be installed in the venv.
> venv: prepare for sh removal and add tests

- src/antsibull_core/subprocess_util.py
- src/antsibull_core/venv.py
- tests/functional/test_venv.py
Most code that decodes stdout/stderr uses `decode('utf-8', errors='surrogateescape')`. So let's also use that in the library code.
> Allow to handle UTF-8 decoding errors

- src/antsibull_core/subprocess_util.py
- tests/units/test_subprocess_util.py
Fixes the problem mentioned in https://github.com/ansible-community/antsibull-docs/pull/122#issuecomment-1502214577.
> Work around line length limit of asyncio.StreamReader

- changelogs/fragments/45-galaxy-v3.yml
- src/antsibull_core/galaxy.py
- tests/functional/test_galaxy.py
Tested by building docs (with antsibull-docs) from a collection on Galaxy where `galaxy_url = "https://beta-galaxy.ansible.com"` is in antsibull-docs.cfg.
> Add support for Galaxy v3 API

- changelogs/fragments/54-config.yml
- src/antsibull_core/schemas/config.py
- src/antsibull_core/schemas/context.py
This reverts parts of commit 81cd1287c9c6980c5cf376ac1b37fb681749b420 from #54, since it broke compatibility.
> Re-add doc_parsing_backend to library context

- src/antsibull_core/subprocess_util.py
This way, callers won't also have to import `subprocess`.
> subprocess_util: export CalledProcessError

- src/antsibull_core/subprocess_util.py
- src/antsibull_core/venv.py
CompletedProcess is apparently a generic [1]. `stdout` and `stderr` are
always `str` in our implementation, so we should annotate them as such.
[1] https://github.com/python/typeshed/blob/7dcec5b3db887f518114486b3e4783dde244186d/stdlib/subprocess.pyi#L86
> subprocess_util: improve type hinting for CompletedProcess

- .github/workflows/antsibull.yml
Maybe this makes the failing CI go away (for now).
The error also happens in the antsibull repo, see https://github.com/ansible-community/antsibull/pull/511 to make it better readable.
> Build compat release with ansible-core 2.14

- src/antsibull_core/venv.py
- tests/functional/test_venv.py
This way you can run `venv.async_log_run()` and always get the correct
python. In VenvRunner, it be `{prefix}/bin/python`. Outside, it should
be `sys.executable`; the first python on $PATH may not be the one that
the program was executed with.
> FakeVenvRunner: replace python with sys.executable

- changelogs/fragments/67-cache.yaml
- src/antsibull_core/ansible_core.py
Neither functools.cache nor functools.lru_cache which was previously
used here works properly with async functions. These decorators cache
the coroutine, but coroutines can only be awaited once, so this falls
apart.
Take the following example:
```
In [1]: from functools import cache
In [2]: @cache
...: async def abc():
...:     return 1234
...:
In [3]: print(await abc())
1234
In [4]: print(await abc())
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[4], line 1
----> 1 print(await abc())
RuntimeError: cannot reuse already awaited coroutine
```
> remove improper usage of @cache on async functions

- changelogs/fragments/67-cache.yaml
- src/antsibull_core/ansible_core.py
* remove improper usage of @cache on async functions
Neither functools.cache nor functools.lru_cache which was previously used here works properly with async functions. These decorators cache the coroutine, but coroutines can only be awaited once, so this falls apart.
Take the following example:
```
In [1]: from functools import cache
In [2]: @cache
...: async def abc():
...:     return 1234
...:
In [3]: print(await abc())
1234
In [4]: print(await abc())
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[4], line 1
----> 1 print(await abc())
RuntimeError: cannot reuse already awaited coroutine
```
* Fix changelog.
---------
> [stable-1] remove improper usage of @cache on async functions (#67)

- .github/workflows/nox.yml
- noxfile.py
- The `codecov/codecov-action` GHA action does not support a `working-directory` option, it's called `directory` instead.
- Pyre does not work when the project isn't installed in editable mode (https://github.com/ansible-community/antsibull-docs/pull/137).
> CI: remove in valid GHA parameters, make pyre work in CI

- changelogs/fragments/82-config-model.yml
- src/antsibull_core/config.py
- src/antsibull_core/schemas/config.py
Revival of #79 that should actually work. The `ConfigModel` there was used in `read_config()`, which turned out to not be used anywhere. Also `read_config()` claimed to return a `ConfigModel` instance, while it actually returned a `Mapping`.
I decided to delete that function as well since fixing it would be more complicated, and it's not really needed anyway since config file loading is handled better by other functions in that module.
> Clean up configuration

- antsibull.cfg
- changelogs/fragments/78-collection-cache.yml
- src/antsibull_core/galaxy.py
- src/antsibull_core/schemas/context.py
- src/antsibull_core/utils/io.py
This allows to reduce the number of requests to the Galaxy server to zero when rebuilding Ansible (or a stable/devel docsite) when all required collection artifacts are already in the cache. Also the filename for the artifact is now determined by antsibull-core, and no longer by the Galaxy server.
Right now antsibull-core doesn't trust the cache and asks the Galaxy server for the filename and the SHA256 checksum of the artifact, and only then checks whether it has a file of that name in its cache, and whether the checksum matches. This means that even if the cache has been populated by the previous `antsibull-build prepare` call a few minutes ago, it has to query the Galaxy server again to make sure it has the latest versions. Especially since Community Galaxy does not allow the content …
> Allow Galaxy downloader to trust collection cache

- antsibull.cfg
- changelogs/fragments/80-ansible-core-cache.yml
- src/antsibull_core/ansible_core.py
- src/antsibull_core/galaxy.py
- src/antsibull_core/schemas/context.py
- src/antsibull_core/utils/hashing.py
- tests/units/test_utils_hashing.py
Add config file options `ansible_core_cache` and `trust_ansible_core_cache` (the latter similar to #78) to the library context to allow caching (and trusting the cache) ansible-base and ansible-core release artifacts.
(I'm not able to test this without trusting the cache right now, so marking it as a draft.)
> Add ansible-core cache

- README.md
This backports changes from the `main` branch that describe the maintenance status of the stable-1 branch.
> [stable-1] clarify maintenance status

- tests/functional/test_galaxy.py
beta-galaxy got a **lot** faster. Potentially due to https://github.com/pulp/pulp_ansible/pull/1408.
> Enable version list test for Galaxy v3 API

- changelogs/fragments/96-version.yml
- src/antsibull_core/args.py
Ref: https://github.com/ansible-community/antsibull-docs/pull/207
> Allow to provide the version to antsibull_core.args.get_toplevel_parser()

- CHANGELOG.rst
- changelogs/changelog.yaml
This fixes an RST syntax error in two changelog entries and regenerates
CHANGELOG.rst.
> Fix RST syntax in changelog

- tests/functional/test_galaxy.py
galaxy.ansible.com was officially switched over to the Galaxy NG
codebase which only supports the v3 API.
For now, we can test the v2 api against old-galaxy.ansible.com.
> test_galaxy: use old-galaxy for v2 API tests

- tests/functional/test_galaxy.py
galaxy.ansible.com was officially switched over to the Galaxy NG
codebase which only supports the v3 API.
For now, we can test the v2 api against old-galaxy.ansible.com.
(cherry picked from commit 1eac01034da9643f517069e5a1a19f78a64c9ae7)
---
`main` used double quotes and `stable-1` used single quotes,
so I did a manual backport to resolve the conflict.
> [stable-1] test_galaxy: use old-galaxy for v2 API tests

- changelogs/fragments/109-typing.yml
- src/antsibull_core/app_context.py
Currently the typing checks fail on `main` (see for example https://github.com/ansible-community/antsibull-core/actions/runs/6478324868/job/17589911927?pr=105). (Having `@contextmanager` in the overloads transforms the typing of the function stub. Also `typing.ContextManager` is a deprecated alias for `contextlib.AbstractContextManager`.)
> Fix typing for app_context

- .github/workflows/antsibull-docs.yml
To avoid breakages due to collections using newer antsibull-docs features.
(Currently nightly fails: https://github.com/ansible-community/antsibull-core/actions/runs/6688280713/job/18170111832)
> CI: antsibull-docs compatibility build: stick to older versions of the collections

- src/antsibull_core/collections.py
- src/antsibull_core/config.py
Follow-up to #105, which broke type checks for antsibull:
```
src/antsibull/build_ansible_commands.py:656: error: Argument 1 to "install_together" has incompatible type "list[str]"; expected "list[str | PathLike[str]]"  [arg-type]
src/antsibull/build_ansible_commands.py:656: note: "List" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
src/antsibull/build_ansible_commands.py:656: note: Consider using "Sequence" instead, which is covariant
```
(https://github.com/ansible-community/antsibull/actions/runs/6766190684/job/18386917570)
> Use Sequence[] instead of list[] for lists of StrPath

- noxfile.py
aiohttp now natively supports Python 3.12.
> Revert "nox: temporarily set AIOHTTP_NO_EXTENSIONS for 3.12"

- noxfile.py
- pyproject.toml
- src/antsibull_core/__init__.py
This allows using the `hatch version` tool to automatically update
versions and makes sure the version metadata of editable installs is
always up to date.
> store package version in __version__ constant

- changelogs/fragments/119-nosh.yaml
- pyproject.toml
- src/antsibull_core/venv.py
Fixes: https://github.com/ansible-community/antsibull-core/issues/34
> remove dependency on `sh`

- changelogs/fragments/122-pydanticv2.yaml
- pyproject.toml
- src/antsibull_core/app_context.py
- src/antsibull_core/config.py
- src/antsibull_core/galaxy.py
- src/antsibull_core/schemas/config.py
- src/antsibull_core/schemas/context.py
- src/antsibull_core/utils/collections.py
- tests/units/test_context.py
pydantic v2 has a fair amount of API changes and deprecations that make simultaneously supporting it and v1 impractical. antsibull, antsibull-docs, and other dependent packages will require some small changes, as well.
---
Fixes: https://github.com/ansible-community/antsibull-core/issues/92
> add pydantic v2 support and drop v1

- changelogs/fragments/131-galaxy-client-context.yml
- src/antsibull_core/galaxy.py
Fixes #121
Needs https://github.com/ansible-community/antsibull-docs/pull/234 and https://github.com/ansible-community/antsibull/pull/570 to pass CI.
> [v3] GalaxyClient: explicitly require a GalaxyContext

- changelogs/fragments/130-old-ansible-rm.yaml
- src/antsibull_core/ansible_core.py
- src/antsibull_core/dependency_files.py
- tests/functional/test_dependency_files.py
- tests/units/test_ansible_core.py
- tests/units/test_parse_pieces.py
Fixes: https://github.com/ansible-community/antsibull-core/issues/123
> [v3] Remove support for old ansible versions

- changelogs/fragments/135-trust-core-cache.yml
- src/antsibull_core/ansible_core.py
Manual backport of #135 to stable-2.
> [stable-2] Don't fetch release infos when trusting the cache. (#135)

- .github/workflows/antsibull-docs.yml
- .github/workflows/antsibull.yml
- CHANGELOG.md
- CHANGELOG.rst
- README.md
- changelogs/changelog.yaml
- changelogs/fragments/3.0.0.yml
- pyproject.toml
- src/antsibull_core/__init__.py
> Release antsibull-core 3.0.0

- .github/workflows/antsibull.yml
This heavily reduces the amount of setuptools warnings.
> Build Ansible 9 in CI instead of Ansible 7

- .github/workflows/antsibull.yml
- changelogs/fragments/160-asyncio-timeouterror.yml
- src/antsibull_core/schemas/config.py
- src/antsibull_core/utils/http.py
- src/antsibull_core/venv.py
Ref: https://github.com/ansible-community/antsibull/pull/600
Ref: https://docs.python.org/3/library/asyncio-exceptions.html#asyncio.TimeoutError
> Restrict pyre-check version for antsibull 0.61.0 compatibility check; fix pyre-check errors; prepare asyncio.TimeoutError removal

- changelogs/fragments/161-context.yml
- src/antsibull_core/app_context.py
pylint complained about this (https://pylint.pycqa.org/en/latest/user_guide/messages/warning/contextmanager-generator-missing-cleanup.html), and this is clearly a real bug. So let's fix it :)
> Make sure that app and lib contexts are cleaned up correctly in case of generator exit

- .github/workflows/antsibull.yml
- changelogs/fragments/163-aiohttp-timeout.yml
- pyproject.toml
- src/antsibull_core/utils/http.py
I'm not sure whether there is an official deprecation, but the conversion code has been removed from `master` (https://github.com/aio-libs/aiohttp/pull/6328) and there's now (since 3.10.0) typing that makes mypy no longer accept floats. The code in 3.10.0 still accepts them though, so this isn't a runtime issue yet.
Also aiohttp 3.3.0+ is required for the timeout parameter that has been used by the GET retry manager since the beginning, so I updated the dependency version range.
Also pyre doesn't think `ClientSession.get` exists anymore with 3.10.0 :roll_eyes:
> Fix typing, use ClientTimeout instead of float, bump aiohttp dependency to 3.3.0+

- .github/workflows/antsibull.yml
- changelogs/fragments/163-aiohttp-timeout.yml
- pyproject.toml
- src/antsibull_core/utils/http.py
Manual backport of #163 to stable-2. (There was a conflict in the change to the workflow, thus no automatic backport.)
> [stable-2] Fix typing, use ClientTimeout instead of float, bump aiohttp dependency to 3.3.0+

- changelogs/fragments/168-collection-meta.yml
- src/antsibull_core/collection_meta.py
- src/antsibull_core/schemas/collection_meta.py
- tests/functional/test_collection_meta.py
Follow-up to https://github.com/ansible-community/antsibull/pull/617. Used by https://github.com/ansible-community/antsibull/pull/620.
> Add collection meta code

- src/antsibull_core/logging.py
> Fix example to use pydantic 2 method

- changelogs/fragments/173-schema-removal.yml
- src/antsibull_core/collection_meta.py
- src/antsibull_core/schemas/collection_meta.py
- tests/functional/test_collection_meta.py
This allows to create all changelog fragments related to deprecated and removed collections automatically.
> Allow to track removed collections in collection-meta.yaml

- changelogs/fragments/174-removed-in-previous.yml
- src/antsibull_core/collection_meta.py
- tests/functional/test_collection_meta.py
This allows to improve https://github.com/ansible-community/antsibull-docs/pull/341 to also create stubs for collections removed in older major Ansible releases.
> Allow removed collection information from previous major releases

- .github/workflows/antsibull-docs.yml
- .github/workflows/antsibull.yml
- .github/workflows/nox.yml
- changelogs/fragments/python-3.13.yml
- noxfile.py
- pyproject.toml
Since Python 3.13.0 has been released, let's use it in CI and officially support it.
> Add Python 3.13 to CI and supported Python versions

- pyproject.toml
We want to get rid of pyre anyway, so let's pin the upper version. Right now (with the latest version) there are some pyre errors that seem to be hard to fix.
> Restrict pyre version

- changelogs/fragments/177-removal-updates.yml
- src/antsibull_core/collection_meta.py
- src/antsibull_core/schemas/collection_meta.py
- tests/functional/test_collection_meta.py
This is needed to generate a consistent changelog if https://forum.ansible.com/t/2811/24 (or similar votes) succeed.
> Allow to update deprecations/removals

- .github/workflows/antsibull-docs.yml
It currently fails due to a mypy update: https://github.com/ansible-community/antsibull-core/actions/runs/15383922657/job/43279041755
> Fix antsibull-docs compat build in CI
