changelogs/fragments/4-devel-detection.yml
src/antsibull_core/ansible_core.py
tests/units/test_ansible_core.py

Fix devel detection

---

changelogs/fragments/6-typing.yml
src/antsibull_core/app_context.py
src/antsibull_core/dependency_files.py
src/antsibull_core/logging.py
src/antsibull_core/utils/collections.py

The latest version of this PR should have typings for all functions and methods in antsibull-core.

Improve typing

---

README.md

@gotmax23's improvements from https://github.com/ansible-community/antsibull-core/pull/17#issuecomment-1340049909.

Update paragraph on maintenance

---

changelogs/fragments/24.yaml
src/antsibull_core/yaml.py

* Add antsibull_core.yaml.store_yaml_stream()
* Update changelogs/fragments/24.yaml
Co-authored-by: Felix Fontein <felix@fontein.de>
Co-authored-by: Felix Fontein <felix@fontein.de>
(cherry picked from commit 3275d7ea6e4018d6771ec4de25b0ba90a8117d84)

Add antsibull_core.yaml.store_yaml_stream()  (#24)

---

pyproject.toml
src/antsibull_core/app_context.py
src/antsibull_core/args.py
src/antsibull_core/compat.py
src/antsibull_core/config.py
src/antsibull_core/schemas/config.py
src/antsibull_core/schemas/context.py
src/antsibull_core/tarball.py
src/antsibull_core/utils/http.py
src/antsibull_core/utils/io.py
src/antsibull_core/vendored/_argparse_booleanoptionalaction.py
src/antsibull_core/yaml.py
tests/functional/aiohttp_utils.py
tests/functional/certificate_utils.py
tests/functional/test_dependency_files.py
tests/functional/test_logging.py
tests/units/test_ansible_core.py

We should probably automate this at some point, but for now running it manual from time to time should be good enough.

Apply isort

---

.github/workflows/antsibull-docs.yml
.github/workflows/antsibull.yml
.github/workflows/pythontests.yml

There seem to be CI problems with stable-1 (https://github.com/ansible-community/antsibull-core/actions/runs/3721050128), this PR is to debug them.

Fix CI for stable-1

---

changelogs/fragments/31-sh.yml
pyproject.toml

(cherry picked from commit 4a72fe2bf5c95eaf2f6c0f2131b2b881bbcfd4b7)

[stable-1] Restrict sh dependency to < 2.0.0

---

pyproject.toml
src/antsibull_core/vendored/collections.py

Relax pylint and pyre-check version constraints

---

README.md
noxfile.py
pyproject.toml

This got forgotten during the linting step.

Lint changelog fragments

---

.github/workflows/antsibull-docs.yml
.github/workflows/antsibull.yml
.github/workflows/pythontests.yml
pyproject.toml

Ref: https://about.codecov.io/blog/message-regarding-the-pypi-package/

[stable-1] Remove codecov dev dependency

---

changelogs/fragments/45-galaxy-v3.yml
src/antsibull_core/galaxy.py
tests/functional/test_galaxy.py

[stable-1] Add support for Galaxy v3 API

---

antsibull.cfg
changelogs/fragments/54-config.yml
src/antsibull_core/schemas/config.py
src/antsibull_core/schemas/context.py

Remove antsibull-docs specific config options

---

src/antsibull_core/galaxy.py

Cleanup galaxy code with dataclasses, and use dict[] instead of t.Dict[]

---

.github/workflows/antsibull.yml

Ref: https://github.com/ansible-community/antsibull-core/pull/58#issuecomment-1510405755

Make antsibull compatibility test output better readable

---

src/antsibull_core/venv.py
tests/functional/test_venv.py

- FakeVenvRunner: remove *log_run staticmethods
- FakeVenvRunner: clarify install_package() docstring

FakeVenvRunner: remove *log_run staticmethods

---

.github/workflows/antsibull.yml

Similar change as #64 for `main`.

[stable-1] Build compat release with ansible-core 2.12)

---

.git-blame-ignore-revs
README.md
noxfile.py
tests/functional/aiohttp_utils.py
tests/functional/certificate_utils.py
tests/functional/test_dependency_files.py
tests/functional/test_galaxy.py
tests/functional/test_logging.py
tests/functional/test_venv.py
tests/units/test_ansible_core.py
tests/units/test_context.py
tests/units/test_parse_pieces.py
tests/units/test_subprocess_util.py

noxfile.py and tests/ were missing (the former also for isort).

Run black on remaining Python files

---

README.md
changelogs/fragments/1.7.0.yml
pyproject.toml

Ref: https://github.com/ansible-community/antsibull-core/pull/106#issuecomment-1752014448

[stable-1] Declare antsibull-core 1.x.y End of Life

---

README.md

Ref: https://github.com/ansible-community/antsibull-core/pull/107

Declare 1.x.y EOL

---

.github/workflows/antsibull.yml
src/antsibull_core/venv.py

With 0.9.19 linting fails:
- https://github.com/ansible-community/antsibull-core/actions/runs/6608598565/job/17947720035
- https://github.com/ansible-community/antsibull-core/actions/runs/6608615267/job/17947578888

Fix linting errors

---

changelogs/fragments/129-deprecated-compat.yaml
src/antsibull_core/compat.py

Fixes: https://github.com/ansible-community/antsibull-core/issues/124

compat: remove deprecated members

---

changelogs/fragments/128-libcontext-appcontext.yml
src/antsibull_core/app_context.py
src/antsibull_core/schemas/context.py
tests/units/test_context.py

[v3] Remove deprecated LibContext/AppContext fields and ansible_base_url normalization

---

CHANGELOG.md
CHANGELOG.md.license
CHANGELOG.rst
changelogs/config.yaml
noxfile.py

[stable-2] Update release workflow and prepare for next release (#144)

---

.github/workflows/nox.yml
noxfile.py

Ref: https://github.com/ansible-community/antsibull-docs/pull/256

nox CI: Use matrix, set up environments separately from running tests

---

.github/workflows/antsibull-docs.yml
.github/workflows/antsibull.yml

CI: use antsibull 0.61.0 and antsibull-docs 2.9.0

---

tests/functional/test_collection_meta.py

Ref: https://github.com/ansible-community/antsibull-docs/pull/331#discussion_r1763569020

Add more tests to check for t.Literal[]

---

.pylintrc.automated
changelogs/fragments/172-removal-schema.yml
src/antsibull_core/collection_meta.py
tests/functional/test_collection_meta.py

Ref: https://github.com/ansible-community/ansible-build-data/pull/458

Collection removal metadata: remove bad check

---

.github/workflows/antsibull-docs.yml
.github/workflows/antsibull.yml
.github/workflows/nox.yml

Fix some issues in GHA workflows pointed out by zizmor (https://github.com/woodruffw/zizmor).

CI: Fix some issues pointed out by zizmor

---

.github/workflows/nox.yml

Ref: https://github.com/wntrblm/nox/issues/943

Make sure the expected Python version is used
